# **Yeison Bermudez**


**1751400**


**Cuaderno #9 - Análisis exploratorio**


**22 de Noviembre del 2019**

Preparación de los datos.

In [1]:
import pandas as pd
df = pd.read_csv('files/indicadores-mundiales.csv', encoding='latin-1')
df.head()

,Ano,Dias para iniciar un negocio,Emisiones de CO2,Esperanza de vida (mujeres),Esperanza de vida (varones),Facilidad para hacer negocios,Gasto en salud ( del PIB),Gasto en salud (per capita),Horas preparar los impuestos,Interes de prestamos,...,Region,Tasa de mortalidad infantil,Tasa de natalidad,Tasa tributaria empresarial,Turismo emisor,Turismo receptivo,Uso de Internet,Uso de energia,Uso de telefonos celulares,Unnamed: 21
0,12/1/2000,NaN,87931.0,71.0,67.0,NaN,3.5,60.0,NaN,10.0,...,africa,3.4,2.0,NaN,193000000.0,102000000.0,0.0,26998.0,0.0,NaN
1,12/1/2000,NaN,9542.0,47.0,44.0,NaN,3.4,22.0,NaN,103.2,...,africa,12.8,5.0,NaN,146000000.0,34000000.0,0.0,7499.0,0.0,NaN
2,12/1/2000,NaN,1617.0,57.0,53.0,NaN,4.3,15.0,NaN,NaN,...,africa,9.0,4.3,NaN,50000000.0,77000000.0,0.0,1983.0,0.0,NaN
3,12/1/2000,NaN,4276.0,52.0,49.0,NaN,4.7,152.0,NaN,15.5,...,africa,5.4,2.7,NaN,209000000.0,227000000.0,0.0,1836.0,0.1,NaN
4,12/1/2000,NaN,1041.0,52.0,49.0,NaN,5.1,12.0,NaN,NaN,...,africa,9.6,4.6,NaN,30000000.0,23000000.0,0.0,NaN,0.0,NaN

El análisis exploratorio se usa para describir propiedades de los datos:

* Localización de los datos.
* Dispersión de los datos.
* Distribución de los datos.
* Relaciones entre los datos.

Pero en términos de la analítica y la inteligencia de negocios, también se usa para responder  preguntas sobre los datos, cuyas respuestas dan insights.

Realice los siguientes ejercicios:

**Ejercicio 1.**-- Construya una tabla de las emisiones de CO2 por continente.

**Ejercicio 2.**-- Cuántos registros hay con datos faltantes?

**Ejercicio 3.**-- Cuáles son los países con menores gastos de salud por región?.

**Ejercicio 4.**-- Cuál es el país con menor esperanza de vida para las mujeres?

**Ejercicio 5.**-- Cuáles son los 10 países con la menor cantidad de población entre 0 y 14 y a cuál región pertenecen?

**Ejercicio 6.**-- Haga un diagrama de barras de las emisiones de CO2 por continente (en los siguientes tutoriales son sobre graficación).

**Ejercicio 7.**-- Haga un boxplot de las emisiones de CO2 por continente (los siguientes tutoriales son sobre graficación).